### ISSUE TITLE
Deployer and bash aliases vs setting the environment in .bashrc file

### ISSUE THREAD

**Issue by gremo** [deployphp/deployer#1429]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 3
| Local Machine OS  | Winddows 10 x64
| Remote Machine OS | CentOS 7

### Description
I'm making an alias for `php` executable in my  `~/.bashrc` file:

```bash
# .bashrc

alias php='/opt/plesk/php/7.1/bin/php'
```
If I login using SSH and do the following:

```bash
source .bashrc
php -v
```
It works in the sense that the correct PHP version is shown. However, **using Deployer the alias is ignored**.

If I use `export PATH=/opt/plesk/php/7.1/bin:$PATH`  instead it **works also in Deployer**.

Am I missing somehting?

**Comment by gremo** [comment]
Heere is the problem https://superuser.com/questions/1245540/alias-does-not-override-path-entries auto closing this!

**Comment by antonmedv** [comment]
Also you can use it: `set('bin/php', '/opt/plesk/php/7.1/bin/php');`

**Comment by H-L** [comment]
Hi,
I'm actually working on **Plesk 17.5.3** to deploy some apps and websites for my agency.

It appears that even if I set `bin/php` manually in my `deploy.php`, it does not fix everything.
When using `deploy:vendors` it will ultimately fail.

The `bin/php` was not loaded correctly in the `bin/composer` (It was printing the `/usr/bin/composer` binary content or calling the global `/usr/bin/php` version instead of my overided version).

I had to do a few `.profile` setup and then override `deploy:vendors` like this to make it work:

```php
// Create .profile to override $PATH variable
run('touch ~/.profile && {{bin/php}}');

// Include $PATH override
$bin_path = 'PATH=/opt/plesk/php/7.1/bin:\$PATH;';
run("echo \"export $bin_path\" >> ~/.profile");

// Source .profile to use the right version of PHP
task('deploy:vendors', function () {
  if (!commandExist('unzip')) {
    writeln('<comment>To speed up composer installation setup "unzip" command with PHP zip extension https://goo.gl/sxzFcD</comment>');
  }
  run('cd {{release_path}} && source ~/.profile && {{bin/composer}} {{composer_options}}');
});
```

**Should I create a new Feature Request / PR to ask/make it work correctly ?**

Any advices would be very welcome !

**Comment by mikestreety** [comment]
Just here to big-up @H-L for this, I had been pulling my hair out for several hours before finding this fix.

For me, the `~/.profile` file already existed, but wasn't being loaded. Could it load it if the file exists?
