### ISSUE TITLE
Proposal: new common recipe for local build

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1450]
What about new default recipe for next deployer v7 with local build?

For example 

```php
require 'build.php';
```

Recipe structure:

* fetch
* build
* release
* upload
* publish

**Comment by Cryde** [comment]
So instead of building the project on the remote, everything will be done on your locale machine ?   
I guess if everything works like now, we could hook before publish to run migrations (on the remote) for instance  
  
Also most of the time (at least for me 😆) computer is more performant than my server

**Comment by antonmedv** [comment]
Actually, now I'm thinking about not new recipe, but instead more flexible `common.php` recipe. 
Which allows for example build assests locally, or do everything locally then upload.

**Comment by staabm** [comment]
hmm I didn't realize that the builtin recipes do the build stuff on the remote.

I wrote my own recipes to run this things on the deployment machine (with runLocally etc)

**Comment by kszymukowicz** [comment]
Local builds is the way to go for two reasons: 
1) CI deployments
2) Its much faster as still ssh commands even with multpiplexing are kind slow

**Comment by kszymukowicz** [comment]
One more reason for local builds: **they can be a lot safer**.

All because its relatively easy to allow ssh to execute only one command like "dep deploy" with ./ssh/authorized_keys settings https://unix.stackexchange.com/questions/60544/allowing-ssh-but-only-to-execute-a-specific-script

So we can give some "very beginner dev" the rights to execute only "/some/wrapper.sh dep deploy" on target machine and not every possible command.
