### ISSUE TITLE
Proposal: parameter description.

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#1459]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 7.x

### Description 
Allow to add description for parameter and retrieve it with `dep help` cli.

```php
set('release_name')
    ->desc('Name of release in {{deploy_path}}/releases folder');
```

**Comment by staabm** [comment]
after thinking a few day about this I came to the conclusion, that I dont think this is the right approach to solve the problem, because

- I need the description for those parameters at coding time (in the editor or IDE), having it in the CLI has no point
- the proposed way will not integrate in a good way with existing tools (or mimics known mechanics from other well known tools)
- this seems to be a workaround for the actual problem: the api is implicit

IMO the solution to the problem would be much simpler: define explicit methods/functions instead, 

e.g.
`set_release_name(/*...$params...*/)` which can be easily phpdoc'ed, described with known syntax.
the phpdoc can be consumed by any IDE or php-aware editor. IDEs can provide autocompletion as the information is available at coding time and not at runtime.

**Comment by antonmedv** [comment]
I like your idea, maybe try to implement it as extension for deployer.

**Comment by staabm** [comment]
maybe I get some time this Friday to look into a small prototype
