### ISSUE TITLE
Empty .env file after laravel deploying

### ISSUE THREAD

**Issue by romaven1** [deployphp/deployer#1576]
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 6.1.0
| Local Machine OS  | Windows 10 with ubuntu virtual machine
| Remote Machine OS | CentOS

### Description 
*I have empty .env file in shared directory after deploying laravel application. I use ssh connect to my vds.*

### Content of `deploy.php`
```
default deploy.php file after dep init with ssh connection options
```

### Output log
*--*

**Comment by antonmedv** [comment]
What is expected behavior?

**Comment by romaven** [comment]
It must be copied from .env.example

**Comment by romaven** [comment]
It's default behavior in composer.json

> "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        ...
    },

**Comment by vesper8** [comment]
having the same issue.. the expected behaviour is indeed that the composer post-install script would create the .env file if it doesn't exist

i think what is happening is that the default envoyer script is creating a blank .env file, thus the composer post-install script doesn't do the copy because it sees the file already exists

what is the proper way to deal with this? is there a way to have deployer copy files from the local directory ?

**Comment by antonmedv** [comment]
Just populate env

**Comment by lommes** [comment]
post-root-package-install is, according to https://getcomposer.org/doc/articles/scripts.md#command-events, only triggered after create-project

Having an empty .env file is because if you choose the laravel recipe it is automatically set as a shared_file. If shared files are missing they are created because recipe/deploy/shared.php touches each shared file before creating the symlink.

So basically what you described is the expected behaviour.
