### ISSUE TITLE
Avoid unnecessary releases

### ISSUE THREAD

**Issue by ahmadmayahi** [deployphp/deployer#1755]
| Q                 | A
| ----------------- | ---
| Issue Type        | Feature Request
| Deployer Version  | 6.3.0
| Local Machine OS  | All
| Remote Machine OS | All

### Description 
Each time I run `dep deploy ...`, the deployer will immediately work, and this is how it suppose to be, but sometimes I don't have any changes in my code, and if I run `dep deploy ...` a new unnecessary release will be created.

For example:

I use `at` command to run deployer every day at midnight:
```bash
at midnight dep deploy prod
```

Deployer has to skip the deployment if no changes were made into the git repo.

### Solution
Whenever deployer finishes, a new file contains the last commit id will be created/updated in `.dep` folder.
The next time we deploy, deployer has to check if the current commit id matches the existing saved one, if so then it will skip the deployment.

I will work on this if accepted.

**Comment by antonmedv** [comment]
Nice idea

**Comment by Chrico** [comment]
Howdy!

In versoin 6.4.7, this new "feature" will break deployment, if you don't have set any `repository`-URL because you're doing e.G. a deploy via CI by running composer + rsync to push the code to server.

This command should only run if `repository` is set: https://github.com/deployphp/deployer/blob/v6.4.7/recipe/deploy/prepare.php#L43-L45

![image](https://user-images.githubusercontent.com/3417446/62861187-e9b44300-bd02-11e9-9877-52c85b55d351.png)

**Comment by ahmadmayahi** [comment]
@Chrico You just need to set the `check_remote_head` as follows:
```php
# your ci deploy file.
set('check_remote_head', false)
```

**Comment by Chrico** [comment]
`check_remote_head` is `false` by default. The problem is this line: https://github.com/deployphp/deployer/blob/v6.4.7/recipe/deploy/prepare.php#L45  which runs even if the `repository`  is not set.

Additonally it could be possible, that the server has no access to the repo itself. So you should probably use `runLocally` instead of `run` here as well.

**Comment by ahmadmayahi** [comment]
@Chrico You are right, I'll look into that. Thanks.

**Comment by antonmedv** [comment]
I dot this. :) See 85aae9fd681028c28b27a5e118d4cd3422484c8d

**Comment by antonmedv** [comment]
Usage:
```php
require 'recipe/deploy/check_remote.php';
after('deploy:prepare', 'deploy:check_remote');
```

**Comment by antonmedv** [comment]
`trim` was added at #628, but I think this is incorrect.
