### ISSUE TITLE
http_user

### ISSUE THREAD

**Issue by metanovii** [deployphp/deployer#1788]
Hi, now user set by command:
`"ps axo comm,user | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | sort | uniq | awk '{print $2}'"`

I think this wrong, becouse this command get me:

www-data   -  this nginx
www-data   -  and this php-fpm

And after a get message from deployer
**Can't detect http user name.                
Please setup `http_user` config parameter.**

**Comment by metanovii** [comment]
U should try **ps axo comm,user | grep -E '[a]pache|[h]ttpd|[_]www|[w]ww-data|[n]ginx' | grep -v root | sort |  awk '{print $2}' | uniq**

**Comment by krukru** [comment]
Hi @metanovii, this is related to #1779, and you are right - it would be better to call `uniq` after printing the usernames. 
Since you have multiple services, but all under the same user, they should be treated as a single http_user candidate.
Could you please provide a hotfix for this issue in the file https://github.com/deployphp/deployer/blob/master/recipe/deploy/writable.php

**Comment by antonmedv** [comment]
#1790
