### ISSUE TITLE
Rsync recipe source is incorrect

### ISSUE THREAD

**Issue by coreyworrell** [deployphp/deployer#2041]
https://github.com/deployphp/deployer/blob/71bd8a99f65b8a594b58ad8f654fa0701c1ba3c6/contrib/rsync.php#L28

This sets the source as `.../vendor/deployer/deployer/contrib` instead of the directory where `deploy.php` is. Using `set('rsync_src', __DIR__);` in the `deploy.php` file will correct this, but it seems the default should already be set to that.

**Comment by antonmedv** [comment]
Can you fix it?

**Comment by coreyworrell** [comment]
@antonmedv I don't know what the "correct" fix would be... It seems to work fine when set to simply `'.'`. If that works then I can submit pull request if you like.

**Comment by antonmedv** [comment]
I think . Will be okay.

**Comment by antonmedv** [comment]
I am cleaning up on issues. Fill free to reopen if needed. 
Also, we have a new section available: [discussions](https://github.com/deployphp/deployer/discussions).

**Comment by DanielRuf** [comment]
This problem still exists. It's because `__DIR__` points to the folder which the script is loaded / executed from so it will be always `contrib` or `deployer.phar/contrib/`.

You would need the arguments from deyploer.php / deployer.phar and use the folder / path from there (if we want to "fix" the contrib recipe).
