### ISSUE TITLE
Copy files between deployment

### ISSUE THREAD

**Issue by nicodmf** [deployphp/deployer#206]
As capistrano as this is a very common pratice to copy files between two deployments.

A common use case is with composer and the vendor dir : it can be simply copied to gain time.

**Comment by elfet** [comment]
Cool thing. Will be implemented 100%.

**Comment by tomzx** [comment]
This can't be done if dependencies have changed. You'd either have to monitor `composer.json/lock` between deployment and decide whether or not it has changed => needs to run `composer install` or blindly assume dependencies won't *ever* change (don't do that).

Furthermore, what kind of use case do you have that makes composer takes *minutes* to install? Are you using `composer update` by any chances? Composer uses a cache mechanism which will make reinstalling the same libraries/dependencies extremely fast since it will be similar to a folder copy, so I don't see the point of that use case.

Let me know if I'm missing something...

**Comment by elfet** [comment]
> Composer uses a cache mechanism which will make reinstalling the same libraries/dependencies extremely fast since it will be similar to a folder copy, so I don't see the point of that use case.
WOW! Cool think! Need more to discuss.

**Comment by nicodmf** [comment]
@tomzx if you copy the entire directory, composer check the states of dependancies. The composer install command is always executed to ensure that a change is taken in charge. Try this work!!!

        rm -rf vendor
        time composer install 
        real    0m54.926s

with only one dev dependancy

and the case is the same with bower : 

       real    0m38.031s

so one minute gain on just two directory and the use case could be make by another local ip datatbases or many other personnal stuff.

**Comment by nicodmf** [comment]
i have retake the test after you affraid me and it's sure if the composer.lock change all dependencies are updated.

i don't know why i don't trust me in this case...

the log : 

composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Removing doctrine/doctrine-bundle (v1.3.0)
  - Installing doctrine/doctrine-bundle (v1.4.0)
    Downloading: 100%

  - Removing michelf/php-markdown (1.4.1)
  - Installing michelf/php-markdown (1.5.0)
    Downloading: 100%

  - Removing sensio/distribution-bundle (v3.0.16)
  - Installing sensio/distribution-bundle (v3.0.18)
    Downloading: 100%

Generating autoload files
Updating the "app/config/parameters.yml" file
Clearing the cache for the dev environment with debug true

**Comment by oanhnn** [comment]
@nicodmf I think you should use symbolic link (shared_dirs and shared_files) for releases.
```php
set('shared_dirs', [
    'app/log',
    'app/cache',
    'vendor',
    'web/upload',
]);
set('shared_files', [
    'app/config/parameters.yml',
    'composer.lock',
]);
```
In the first deploy (`composer install`) all vendors will install to `shared/vendor` folder and make content for `composer.lock` file. In next time deploy (`composer install`) will read `shared/composer.lock` file and find installed vendors in `shared/vendor`. If vendors haven't any update, it will not change and generating autoload files.
I think current spec of deployment symfony project is ok.

**Comment by nicodmf** [comment]
@oanhnn If you make that you cannot have roolback

**Comment by KingCrunch** [comment]
Afaik in capistrano3 this task is actually a recipe and it is pretty simple (failsafe, "stupid", ... :wink: ). Indeed it simply copy files and folders from the current release to the release candidate. I think that's the best approach, because it leaves the both releases entirely independent. And as a recipe it is optional anyway.

**Comment by elfet** [comment]
What about having deploy option '--copy' which will copy entire old release to new one?
'''
dep deploy  --copy
'''

**Comment by tomzx** [comment]
It would make more sense if that was set in the config and not at deploy time.

**Comment by oanhnn** [comment]
Agree with @tomzx

**Comment by marcosh** [comment]
I am just starting to use deployer and I think that copying the whole directory of the release and then performing a `git pull` is certainly better the doing every time a `git clone`. This will surely save time also with composer, since it will have only to download the new dependencies specified in the `composer.lock` file and not all of them.

Another option could be renaming the oldest release directory (which would anyway be deleted during the cleanup) and start from there. In such a way, we would save even the time of copying the whole release.

In both cases I think that this should not be specified at deploy time, but in configuration, having various options to choose from.

**Comment by johnny-bit** [comment]
This can be acomplished using `rsync` recipe. there's task `rsync:warmup` which does exactly what You need - copies last release to new one. You don't have to rsync anything up there, but simply after `rsync:warmup` do `git pull` instead of `git clone`.

**Comment by AlexStansfield** [comment]
In 2.x I added a feature for copy vendors based on the value of the parameter composer_copy_vendors. I just noticed that it was missing in 3.x a few hours ago and started reimplementing it before I found this issue.
