### ISSUE TITLE
No stable tag for PHP 8

### ISSUE THREAD

**Issue by Bilge** [deployphp/deployer#2345]
Whilst I understand the next major version of Deployer will support PHP 8, it would greatly ease upgrading if the 6.x branch also supported PHP 8. If it technically does already, adding the tag should be trivial. Having the tag means users can upgrade to PHP 8 and later upgrade Deployer, instead of having to do both at the same time. Therefore having a stable PHP 8 tag now is important, rather than waiting for Deployer 7 release.

**Comment by antonmedv** [comment]
This is make sense. Will release patch for php8.

**Comment by dejury** [comment]
Any update on this one yet?

**Comment by antonmedv** [comment]
Done. Released v6.8.1.

**Comment by dlakomski** [comment]
@antonmedv there is no such version in releases.

**Comment by Bilge** [comment]
Seems he forgot to push the tag...

**Comment by antonmedv** [comment]
Yes, I did it, but have to revoke the release and deleted the tag as it not that simple. Due to:
https://github.com/deployphp/deployer/issues/2348
https://github.com/deployphp/deployer/issues/2352

Please follow instructions here: https://github.com/deployphp/deployer/discussions/2351

**Comment by aboks** [comment]
We were 'lucky' enough to update deployer in the short timeframe that 6.8.1 existed. Because of that, I just discovered that 6.8.1 (i.e. commit 042d1006906002ef580e5453894c4fd47180701e) is based on the commit of release 6.4.5 (its parent is commit be14a4f757cff060ebd3df661df12687e5fbc25e) rather than on 6.8.0. That caused all the features and bugfixes added between 6.4.5 and 6.8.0 to be 'disappeared' in 6.8.1.

With 6.8.1 being retracted that is not a big issue anymore, but branch 6.x still points to the commit that was previously release 6.8.1. I think it would be a good idea to reset that branch to the commit that is version 6.8.0, to not have these 'missing features/bugfixes' problems again when ever trying to release a version 6.8.2.

**Comment by antonmedv** [comment]
Will do please open new issues to not forget.

**Comment by Bilge** [comment]
Seems this issue should be reopened.

**Comment by antonmedv** [comment]
Updated to 4e243a6 (HEAD -> 6.x, tag: v6.8.0, origin/6.x) Release v6.8.0
