### ISSUE TITLE
Escape commandline arguments

### ISSUE THREAD

**Issue by Blackskyliner** [deployphp/deployer#271]
I think the recipies should use http://php.net/manual/de/function.escapeshellarg.php for their shell command arguments. (In general, cmd arguments should be escaped somehow, if not using escapeshellarg at least use single quotes for parameters which could contain spaces or escape the spaces)

As an example which should currently break, only through looking at current code: https://github.com/deployphp/deployer/blob/master/recipe/common.php#L175

Because they are just concatenated with an space and then directly set into the cmd-line it will fail for folders with an space. Or am I wrong here? Its just an observation I did while looking at the code for an other issue, not tested though.

**Comment by elfet** [comment]
I don't see bug here. Can you create example task?

**Comment by Blackskyliner** [comment]
I just keep myselft to the linked sourcecode with this example:

```
$dirs = join(' ', ['some/folder/with spaces/in/the/path', 'some/other/folder/without/spaces']);
echo ("sudo chmod +a \"`whoami` allow delete,write,append,file_inherit,directory_inherit\" $dirs");
```

would then expand to:

```
echo ("sudo chmod +a \"`whoami` allow delete,write,append,file_inherit,directory_inherit\" some/folder/with spaces/in/the/path some/other/folder/without/spaces");
```

where as it would try to chmod the folders:

- some/folder/with 
- spaces/in/the/path
- some/other/folder/without/spaces

but the expected behaviour would be:

- some/folder/with spaces/in/the/path
- some/other/folder/without/spaces

**Comment by elfet** [comment]
```
'some/folder/with spaces/in/the/path'
```
This is definitely wrong. You should now write like this.

**Comment by Blackskyliner** [comment]
So you say I have to escape the directories for things like writable dirs myself if they contain a space?

**Comment by elfet** [comment]
Of course.

**Comment by elfet** [comment]
Or use escape func)

**Comment by nkovacs** [comment]
You can't escape `shared_files` because it uses dirname: https://github.com/deployphp/deployer/blob/de134782c36f9ffd48ba661adaee50dd522ff179/recipe/common.php#L254

For example:

```
<?php

var_dump(dirname(escapeshellarg('some dir with spaces/test.txt')));
```

You'll get `string(30) "'some dir with spaces"`, which will break the shell command.

Besides, I don't understand why the burden of escaping is left to the user. Why can't the common recipe do it?

**Comment by Blackskyliner** [comment]
I guess because it's hard to infer what should be escaped in which way.

The one argument could be a path so you could escape spaces with `some/dir\ with\ spaces/` but then the next argument is a string which gets `--some-arg='some argument where I do not want escaped strings, maybe'`.

The thing is, that it's sometimes not so clear, at least to me, where I have to escape and where not. Or better where I can escape and where not... I guess the simplest approach would be to have some Command Generator thingy with builder Pattern where the things you put in are escaped in a context sensitive manner.

**Comment by nkovacs** [comment]
I don't think it's hard at all. For example, `shared_files` is an array of paths. Why would you not want to escape them all? It's counter-intuitive (php's functions do not need escaped paths), and all it enables the user to do is inject arbitrary arguments and commands where they should not.

You don't have to treat paths differently, you can escape them with single quotes using `escapeshellarg`.

The CommandGenerator is a good idea, but you still have to change the recipes so that `shared_files`, `shared_dirs` etc. are escaped. Whether you do that with a CommandGenerator or just string concatenation with `escapeshellarg` doesn't matter.
