### ISSUE TITLE
Allow add() in deploy.yaml

### ISSUE THREAD

**Issue by solverat** [deployphp/deployer#2780]
Using this as example:
```yaml
import: recipe/symfony.php

config:
    shared_dirs:
        - my_dir
```

Result of `get('shared_dirs')`: `['my_dir']`

But sometimes I may want to have a result like this: `['var/log' ,'my_dir']`. 
A solution would be to move the `import` node after the `config` node, but this might be error-prone.

WDYT?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/2780">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/2780/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/2780/pledge.svg">
</picture>
</a>

**Comment by antonmedv** [comment]
I’m thinking on adding add: option.

**Comment by Schrank** [comment]
YAML can this already, maybe this helps: https://stackoverflow.com/q/24090177/1480397

**Comment by luke83** [comment]
I'm in the same situation explained by @solverat but for a laravel recipe, i need to "append" values to following configurations: shared_files, writable_dirs, writable_dirs.

Solution by @Schrank is not applicable because initial values are there by laravel recipe using `add` function, they are not in the yaml, so we cannot refer them.

Solution by @antonmedv will be ideal to "append" values instead of "set" them.

Please let me know if i can help in any way, i'm not deep in new version code, but i can give it a try or i can help to validate the solution once in place!

**Comment by peterjaap** [comment]
In PHP you can use add() instead of set()

**Comment by luke83** [comment]
Hi @peterjaap,
yes i know, the issue is to have something similar in yaml new format (7.x)

**Comment by antonmedv** [comment]
I think this will be in Deployer v7.1. Right now I want to release v7.0.

**Comment by luke83** [comment]
> I think this will be in Deployer v7.1. Right now I want to release v7.0.

any news about this feature request?

**Comment by Schrank** [comment]
@antonmedv We have the same problem. Do you want an "add" or is it ok for the moment to merge by default?

**Comment by Schrank** [comment]
And I'm talking about

- add('shared_files', ['.env']);
- add('shared_dirs', ['vendor', 'node_modules']);
- add('writable_dirs', ['bootstrap/cache', 'storage']);

But happy to take care of more
