### ISSUE TITLE
Environment vs Global variables

### ISSUE THREAD

**Issue by ZeeCoder** [deployphp/deployer#292]
I wanted to contribute to the documentation about global variables, since there's almost nothing about them.

But then I realized, that even I don't really know that much, so here are some questions:
 - What is the difference between environment and global variables?
 - When should I use which?

**Comment by elfet** [comment]
Global parameters is what need to be really global, such as repository, etc. 
Everything else must be a environment specified(related to server, deploy path, branch to deploy, stages, etc.)

**Comment by elfet** [comment]
Also in future i plane to refactor global parameters, and will be available to set global parameters from on evn, and changes apper on all envs (talking about parallel deployment), this allow to write task which will set one release number for all envs.

**Comment by rjanja** [comment]
@elfet that sounds great. I've been struggling with sharing variables from a sanity-checking task in a parallel deployment. Currently I'm listing out the servers by role that the deploy would affect, and confirming branch/tag. Unfortunately I can't keep all the logic there because that task is isolated from the other workers.
