### ISSUE TITLE
Autoloaded classes are no longer available in deploy.php

### ISSUE THREAD

**Issue by Bilge** [deployphp/deployer#3070]
- Deployer version: v7.0.0-rc.8
- Deployment OS: Windows

Since `vendor/bin/dep` became `vendor/bin/deployer.phar`, it is no longer possible to use non-Deployer classes in `deploy.php`.

The autoloader must be manually required with (`require_once __DIR__ . '/vendor/autoload.php'`). There is no note about this regression in the [UPGRADE.md](https://github.com/deployphp/deployer/blob/master/docs/UPGRADE.md).

**Comment by antonmedv** [comment]
Probably this should be fixed in bon/php and also include correct autoload.php as well.

**Comment by refsz** [comment]
I have a custom composer package "refsz/deployer". One of its dependencies is "deployer/deployer". With this package I extend Deployer with custom functions and manage my recipes there. For deployment I install this package globally in the pipeline. Since this change I have the same problems as @Bilge .

But since I install the package globally I had to require the global autoload.php. 
`require_once dirname(DEPLOYER_BIN) . '/../../autoload.php';`

**Comment by Bilge** [comment]
Pretty sure I said that, but credit where credit's due, right?

**Comment by joelpittet** [comment]
@Bilge sorry, I really meant to the `custom composer package` part of refsz's comment but really doesn't matter we all have the same problem and workaround. Thanks for suggesting the workaround @Bilge!

**Comment by antonmedv** [comment]
I’m going to bring back source code and phar as dep bin.

**Comment by joelpittet** [comment]
Thanks @antonmedv that will help with transitioning my team! Almost ready to make the switch to 7! Also encouraging numbers I saw when testing them `6` took my deploy `2m 7s` and `7` took `1m 27s`!

**Comment by Bilge** [comment]
This still isn't fixed in v7.0.2 using `vendor/bin/dep`.

**Comment by mbrodala** [comment]
I guess exactly this is the necessary fix and makes sense.

**Comment by antonmedv** [comment]
Deployer v8 now is releases and uses normal autoload.php composer path. So the issues should be fixed in Deployer v8.
