### ISSUE TITLE
Implement default_selector

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#3198]
@antonmedv Not sure if this would work but around here in the `SelectCommand`
https://github.com/deployphp/deployer/blob/42734c5f352e04279097fde6f4cc9182e342755b/src/Command/SelectCommand.php#L56
Could we have a hook to provide a default selector? I'd sure enough set it to `stage=staging`

_Originally posted by @joelpittet in https://github.com/deployphp/deployer/issues/2676#issuecomment-1050429787_

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/deployer/issues/3198">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/deployer/issues/3198/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/deployer/issues/3198/pledge.svg">
</picture>
</a>

**Comment by juouy** [comment]
Honestly i cannot understand why there's still no "default_stage" from 6.x replacement as of 7.x.
Why should it be implemented? 

By default deployer connects to all defined hosts and attempts to begin deployment to all of them. 
Imagine you have dev and prod and it'll begin deployment everywhere just because you did not specify your label. In certain situations this can lead to dangerous mistakes and default_stage was the security switch, where you could define dev environment as default one.
