### ISSUE TITLE
@antonmedv Adding the exception is a breaking change in the following case:

### ISSUE THREAD

**Issue by antonmedv** [deployphp/deployer#3318]
@antonmedv Adding the exception is a breaking change in the following case:

We can't run some build commands on the remote server so we rely on "localhost" to locally pull and build the project and then we send all the files to the remote via rsync.

Since 7.0.2, we can't deploy anymore because the task `yarn:install` which use `previous_release` is now throwing an exception.

The thing is, we call `deploy:release` before using `previous_release` so the config should exists !

Here is an excerpt of our `deploy.php` file:

```php
// Set the source for rsync
set('rsync_src', '/home/www-data/deploy_local/current');

// Create a localhost host which will be used to build the project locally
$localhost = localhost()
    ->set('deploy_path', '/home/www-data/deploy_local');

// Declare the target host for production
host('production')
    ->set('hostname', 'xxx.xxx.xxx.xxx')
    ->set('deploy_path', '/var/www/test');

// This is the main task which is call to deploy the projet
task('custom:deploy-ci', function () use ($localhost) {
    // We start by building the project on the localhost host
    on($localhost, function () {
        invoke('local:build');
    });

    // Then we prepare and push the code to the remote server
    invoke('remote:release');
})->desc("Project deployment");

// This task should only be used on the "localhost" host
task('local:build', [
    'deploy:setup',
    // We call deploy:release so "previous_release" should be set
    'deploy:release',
    'deploy:update_code',
    'deploy:vendors',
    // Yarn recipe start with "if (has('previous_release'))..."
    // which throw an exception and I cant' understand why
    'yarn:install',
    'deploy:symlink',
])->hidden()
  ->desc("Local build of the assets");

task('remote:release', [
    'deploy:setup',
    'deploy:lock',
    'deploy:release',
    'rsync:warmup',
    'rsync',
    ... // some other irrelevant command
    'deploy:unlock',
    'deploy:cleanup',
])->hidden()
  ->desc("Remote deployment");

fail('custom:deploy-ci', 'deploy:failed');
after('deploy:failed', 'deploy:unlock');
after('custom:deploy-ci', 'deploy:success');
```

Do you need me to create a dedicated issue or should this one be opened again ?

Thx for your time !
Tristan

_Originally posted by @Tchanove in https://github.com/deployphp/deployer/issues/3218#issuecomment-1256004078_

**Comment by Tchanove** [comment]
@antonmedv Continuing in this issue:

> Question: why do you do local build with all those steps?

Because we are limited to file transfer only to the remote server. No git, no composer, no nodejs... Only good old ssh access and file transfer.

So the pipeline is:
- On CI trigger
  - Pull and build dependencies (composer, yarn) locally (`local:build`)
  - Then push the generated code via rsync to the remote (`remote:release`)

But no matter why I do that, there is clearly a bug in the `deploy:release` or in something else because this code:
```
    on($localhost, function () {
        invoke('local:build');
    });
```
invoke the `local:build` task on the `localhost` host. So if the `local:build` task run the `deploy:release` task, the config `previous_release` should have been defined right ?

**Comment by antonmedv** [comment]
This runs on another host (loxalhost). Closure doesn’t know about other host anything. 

For local build you don’t need all this boilerplate with release and update_code stuff. 

Why all this task is needed?

    'deploy:setup', Whay setup on local?
    // We call deploy:release so "previous_release" should be set
    'deploy:release',  Why?
    'deploy:update_code',
    'deploy:vendors',
    // Yarn recipe start with "if (has('previous_release'))..."
    // which throw an exception and I cant' understand why
    'yarn:install',
    'deploy:symlink',

**Comment by Tchanove** [comment]
Well theses tasks are here because of how deployer work.

If we want to `deploy:vendors` in order to install composer dependencies, we need to clone the code base.
So we do `deploy:update_code`. But this task clone the repo in the `release_path` so we need to call `deploy:release`.
This task need to have the `.dep` directory to exists because it try to right the release number, so we need to call `deploy:setup`.


To give you a better understanding of the process, the command `dep custom:deploy-ci production --revision=$CI_COMMIT_SHA -v` is run by Gitlab CI inside a docker container.
This container _contains_ only the `deploy.php` and `deployer/deployer=^v7.0` installer via composer, no code, nothing, it is clean on each startup.

So I must do `deploy:update_code` to pull the git repository in order to build the project.
The I do `deploy:vendors` to install composer dependencies.
Then `yarn:install` to install nodeJs dependencies.
I omitted a custom yarn task which build the project by running a command but it's irrelevant I think, here is the task:
```
task('yarn:run', function () {
    run("cd {{release_path}} && {{bin/yarn}} run production");
});
```

After all of this, I use rsync via `contrib/rsync` to warm-up (`rsync:warmup` copy current to release on the `production` host) and then upload via rsync only changed files with `rsync`.

By the way, we used this strategy for more than 4 years and we love Deployer, that's why I'm so passionate in my response. I hope I'm not giving the impression of being angry or what, I just want to help to keep Deployer as good as ever :smile:

**Comment by Tchanove** [comment]
Btw, I dug in the code and understand better why it was functioning before 7.0.2.

The task `yarn:install` is as follow:
```
task('yarn:install', function () {
    if (has('previous_release')) {
        if (test('[ -d {{previous_release}}/node_modules ]')) {
            run('cp -R {{previous_release}}/node_modules {{release_path}}');
        }
    }
    run("cd {{release_path}} && {{bin/yarn}}");
});
```

By looking at the code you could think that if there is no previous release, ` if (has('previous_release'))` will return `false` ?

Well before 7.0.2 it returned false but not anymore because now `previous_release` exists and is a callback function throwing an exception if it was set before.

This is due to the fact that the function `has()` look into the config of the current Context (here `localhost`).
There is no `previous_release` in this context so the function look to the parent configuration and here is the problem.

The `yarn:install` function should only look for the `previous_release` of the current context no ?
Changing `if (has('previous_release'))` to `if (currentHost()->hasOwn('previous_release'))` check only if the current host has a previous release and I think it makes more sense because we don't really care if the parent context has any previous releases no ?

Let me know if it makes sense or if I'm overlooking something.

(Btw, for now we fixed our config by adding `set('previous_release', false);` here:
```php
    on($localhost, function () {
        set('previous_release', false);
        invoke('local:build');
    });
```
Dirty, but it do the job)

**Comment by Tchanove** [comment]
@antonmedv Btw, I found another (linked) case where throwing an exception in `previous_release` is unexpected !

On the very first deployment, I create a directory on my server in `/var/www` name `project`. Directory is empty.
So I set `deploy_path` to `/var/www/project`.

Here is my `deploy` task where I want to simply clone, install PHP deps, install nodejs deps, build frontend assets and publish :
```php
task('deploy', [
   'deploy:prepare',
   'deploy:vendors',
   'yarn:install',
   'yarn:assets',
   'deploy:publish'
])
```

Here, on the very first deployment, when `deploy:release` (part of `deploy:prepare` task) is called, [it check for any previous release and if there is at least one, it push it in `previous_release` config](https://github.com/deployphp/deployer/blob/master/recipe/deploy/release.php#L145):
```php
    // Add to releases list.
    array_unshift($releasesList, $releaseName);
    set('releases_list', $releasesList);

    // Set previous_release.
    if (isset($releasesList[1])) {
        set('previous_release', "{{deploy_path}}/releases/{$releasesList[1]}");
    }
```

But if we are on the very first deployment, the release least contains only the current release, there is no `$releasesList[1]` so `previous_release` is never set ! And when we arrive at `yarn:install` tasks which use `get('previous_release')`, it throw an exception.

Imho, this is another example of why the commit adding the exception should be reverted.
It maybe can evolve to something less dependent of `deploy:release` by using `get('releases_list')` (or `get('releases_log')` directly) without counting the release in progress if there is one ?

Let me know what you think about all of this :)
