### ISSUE TITLE
Please login as the user \"ubuntu\" rather than the user \"root\ during provisioning

### ISSUE THREAD

**Issue by florentdestremau** [deployphp/deployer#3542]
- Deployer version: 7.2.1
- Deployment OS: ubuntu 20.04

I have a OVH VPS that I provisioned. I can only login via ssh on the `ubuntu` user with sudo enabled. I tried the `dep provision -o become=root -o remote_user=ubuntu` even while having the `deployer` user in my deploy.php config (as stated in the docs).

Everything went fine until `provision:website` where it seems to force the deployer user but I can't access the server with this user. When investigating I ended up finding that my rsa key was added like this:

```
# /home/deployer/.ssh/authorized_keys
no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="echo 'Please login as the user \"ubuntu\" rather than the user \"root\".';echo;sleep 10;exit 142" ssh-rsa XXXX-MY-KEY-XXXXXX
ssh-rsa XXXX-MY-KEY-XXXXXX
```
As you can see my key is added twice AND with a guard preventing me to login.

Looking further it seems it's copying my standard root user `authorized_keys` instead of creating a usable configuration.

**Comment by dvdinbox** [comment]
@antonmedv @florentdestremau 

Is there any workaround to this? I'm trying to deploy to an aws ec2 and it reports

```
[ec2-****.us-east-2.compute.amazonaws.com]  error  in website.php on line 16:
[ec2-****.us-east-2.compute.amazonaws.com] run [ -d ~/public ] || mkdir ~/public 
[ec2-****.us-east-2.compute.amazonaws.com] Please login as the user "ubuntu" rather than the user "root".
```

Here's some things I tried

1) Allowed root ssh into the instance. The strange thing is I'm now able to ssh as root, but deployer still returns  the 'Please login as the user "ubuntu" rather than the user "root"' error

2) Tried to manipulate the problem line of code in provision:website. I thought I'd be able to make changes in the local vendor\deployer\deployer\recipe\provision\website.php file and see the effects of the changes in real time. I can't figure out to make changes to code and test the effect of the changes. Note that I'm relatively new to this php ecosystem.

**Comment by florentdestremau** [comment]
> > Looking further it seems it's copying my standard root user authorized_keys instead of creating a usable configuration.
> 
> Didn’t get this part.

What I mean is that OVH (my cloud provider) sets up a special script on top of my ssh key so that it gracefully prevents login. I didn't look too much into the code, but it would seem that it copies the root `.ssh/authorized_keys` into `/home/deployer/.ssh/authorized_keys` so it perpetuates the script thing. If I remove it from the root ssh file then it works as expected.
