### ISSUE TITLE
Migrating from capistrano to deployer

### ISSUE THREAD

**Issue by gordalina** [deployphp/deployer#359]
@uran1980 raised this question on the recipes repo.

It is an important step having a migration from an accepted and widespread tool to deployer, this will allow deployer to gain new users with the least amount of friction.

I'm not versed in capistrano, it would be nice if someone with experience with capistrano can write a migration process.

**Comment by ZeeCoder** [comment]
I have experience with [Capifony](http://capifony.org/), so I might be able to write something, but it would took some time, since there would be a lot of testing involved.

**Comment by elfet** [comment]
@ZeeCoder what's will be awesome! I think we need how-to's for than on deployer.org.

**Comment by uran1980** [comment]
Thanks, folks) This will be cool!

**Comment by ihsanudin** [comment]
@ZeeCoder : I use Capifony also, and it's really easy to migrate from capifony to deployer.

@gordalina : i think you don't need special docs to migrate from capistrano because deployer is easier than it

**Comment by ZeeCoder** [comment]
Even though I agree, that Deployer is easier and migrations is very easy, I still think, that the more such tutorials we have, the better.
If I'm a developer that never used Deployer before, I could be intimidated by the task, since I don't know the tool well enough.

Also, if I'm searching for a deployment tool as a developer, and I see that Deployer supports a myriad of frameworks with detailed explanations of the recipes, **and** it has tutorials about migrating from other tools, I would certainly be chosing Deployer over others.

**Comment by ihsanudin** [comment]
@ZeeCoder : Many people doesn't have experience with ssh, public key, ssh config and many things of technical (especially the flow of how the code will be download from the repository and why i have an error when i try to download the repository from my own server)

I think will be better to write a doc for how to use deployer step by step

#sorry for my bad english

**Comment by johnny-bit** [comment]
How about also have some examples for combining builtin recipes, 3rd party recipes and own code into something *nice* Would be cool to have something like *best practices* or *advanced sample recipes* ;)

**Comment by ZeeCoder** [comment]
@ihsanudin @johnny-bit Those are both good ideas, I think we don't have to chose between these, we could just start writing all kinds of documentation. :)
Of course, the website has to be updated then slightly, so that it would stay clean, but at the same time the user should be able to navigate between the documentations easily.

**Comment by johnny-bit** [comment]
There could also be something like (just writting idea):

# Recipe XYZ

[...]

### Saples using this recipe

- Deploy to ToiLet
- Wordpress + Laravel + Twig
- Local building + remote syncing
- Send files by Pidgeon

**Comment by gordalina** [comment]
Great documentation is a major contribution for the popularity and adoption of open source software.
It's one of those things that more you have, the more advantages you have.

**Comment by gordalina** [comment]
@johnny-bit tutorials for 3rd party recipes, especially for custom workflows are really important!

**Comment by ZeeCoder** [comment]
Note: I still didn't have any time to write about the migration process, because I'm working on an API draft for Deployer v4.

If someone would like to tackle this task, feel free to do so. :+1:

**Comment by webdevilopers** [comment]
Coming from Capifony and Capistrano v2 I'm doing my first steps with Deployer.
I tried Magallanes / MagePHP in between.

My main migration questions dealed with Symfony tasks like:
- sharing files e.b. "parameters.yml" and configure in interaction mode once using "parameters.yml.dist" and automatically symlinking
- not using git clone on remote but pushing copy from local machine to remote target
- file structure Symfony v2 vs. v3
- assetic Symfony v2 vs. v3

**Comment by ihsanudin** [comment]
@webdevilopers : i'm a symfony developer and i just confirm, deployer use git clone instead local copy.

You can use extra param `-vvv` for more verbose
