### ISSUE TITLE
Magento 2 - Outdated generated code

### ISSUE THREAD

**Issue by torhoehn** [deployphp/deployer#3652]
- Deployer version: 7.3.1
- Deployment OS: Ubuntu 18.04

For us it often happens that the files in `generated/code` are outdated. It seems like these are generated on basis of the release before.

Is this a known issue? Is there any reason why https://deployer.org/docs/7.x/recipe/magento2#magentoset_cache_prefix is only part of the artifact deployment?

**Comment by valguss** [comment]
Ho @torhoehn 
The cache_prefix is not part of the artifact deployment so you should be able to use it without artifacts. There's a couple of fixes coming in the next release of deployer though for it. We've seen occasional issues like you;ve described which is why I built the cache_prefix setup.

I'd strongly advise you check it on a staging site before deploying to a production environment though just to make sure

Like i said though, might be best to wait for the next release

**Comment by torhoehn** [comment]
@valguss Thanks for keeping us updated here.

Ah now I see that there was a change between master and latest released version. In the latest released version it depends on the variable `use_redis_cache_id` which is only checked during artifact deployment, but this was changed in `master`.

**Comment by torhoehn** [comment]
@valguss While using `deployer/deployer:dev-master` I receive the following error:

```
Error  in magento2.php on line 474:
Class "Symfony\Component\VarExporter\VarExporter" not found
```

Is it correct that `symfony/var-exporter` is a dev requirement or should this be moved to `require` section?
https://github.com/deployphp/deployer/blob/master/composer.json#L62

**Comment by valguss** [comment]
Think I had it in there but was removed. Let me add back in again
