### ISSUE TITLE
Is there a way to deploy without VCS ?

### ISSUE THREAD

**Issue by benjamingauthier** [deployphp/deployer#389]
Hey guys,

I need to use Deployer in the way to deploy a local directory (which is part of a Git repository).
I've tried *upload* function, but it's just make a copy and not a real deployment.

Is it possible with Deployer to do this ?

Thanks ! :)

PS : I'll upadte the docs, if a way exists.

**Comment by johnny-bit** [comment]
Sure there is: look @ rsync recipe in [deployphp/recipes](http://github.com/deployphp/recipes). You'll have to configure rsync src for it to send Your dir instead of deploy:update_code and it should be OK

Your recipe should then basicly have something like this in it:

```php
task('deploy', [
    'deploy:prepare',
    'deploy:release',
    'local:update_code',
    'rsync',
    'deploy:symlink',
    'cleanup',
])->desc('Deploy your project');
``` 

local:updte_code is for local code update. If You want to send Your repo and not create another - then omit that :)

**Comment by benjamingauthier** [comment]
Thanks four your reply :)

I forget to precise an important information. I'm using Deployer from Windows to Ubuntu. 

rsync, seems a complicated way on Windows. 

I'll make some test today, I'll keep you in touch !
