### ISSUE TITLE
Move deploy.php to subdir

### ISSUE THREAD

**Issue by sergiocarracedo** [deployphp/deployer#396]
I create a recipe for Drupal 7, this recipe is complex and use external libraries, for example, for crate the drupal settings.php file and upload it.

I dont want my recibe files in the project's root dir, i move them to .deployer, but deploy.php still in root dir.

is it posible move deploy.php search to this subfolder?

And i want to share my drupal 7's recipe, how i do? Creating a fork?

**Comment by johnny-bit** [comment]
generally, I'd simply remove `deploy.php` and libraries in subdir in some task, maybe even right after `deploy:update_code`. That would actually be sane thing to do - in my `rsync` recipe, by default `deploy.php` is ignored from syncing.

And that brings us to recipe - generally I'd recommend creating fork & PR against deployphp/recipes, however since it's framework specific, maybe @deployphp/maintainer (pinging @elfet - have I linked that correctly)  would rather suggest fork and PR against deployphp/deployer :smiling_imp:

**Comment by kenjis** [comment]
I don't know this is what you want or not. But I do like this:
https://github.com/kenjis/codeigniter-deployer/tree/master/deploy

For your information.

**Comment by sergiocarracedo** [comment]
Thanks a lot @kenjis it's a great solution. I was looking for a solution like rocketter who put evey deply files in a folder. In this case, It's easy add the folder to .gitignore, but your solution es similar, i'll try it

**Comment by oanhnn** [comment]
I think you can try:
```
$ bin/dep -f=path/to/deploy.php
```
and file `deploy.php` will be in anywhere :smile:

**Comment by elfet** [comment]
Can anyone add docs about `-f`? :sunglasses:
