### ISSUE TITLE
dep init command

### ISSUE THREAD

**Issue by elfet** [deployphp/deployer#407]
Add `dep init` command which generate `deploy.php` file from template. 
```
dep init [template=symfony|composer|common]
```

**Comment by ZhukV** [comment]
I create this feature.

**Comment by elfet** [comment]
Please, create a separate branch on this repo.

**Comment by ZhukV** [comment]
ok

**Comment by ZhukV** [comment]
@elfet where i can see the resources of template?

**Comment by elfet** [comment]
Hmmm. My deploy script:
```php
<?php
require 'recipe/symfony.php';

serverList('app/config/servers.yml');

set('repository', 'git@github.com...git');

task('reload:php-fpm', function () {
    run('sudo /usr/sbin/service php5-fpm reload');
});

after('deploy', 'reload:php-fpm');
```

**Comment by ZhukV** [comment]
1. Add **Initializer** system.
2. Add **Template** system for easy create any templates.
3. Add the command for initialize deploy configuration.
4. Add tests for new code.

Now add only **common** and **composer** templates, because i not understand how use another systems.

@elfet maybe you can adds another templates?

**Comment by oanhnn** [comment]
:+1:

**Comment by ZhukV** [comment]
@elfet fixed: 235de6e4c56f84dd698468292b21b3ad25f8f989

**Comment by ZhukV** [comment]
@elfet merge to **master**?

**Comment by oanhnn** [comment]
@ZhukV Can you fix coding style follow https://styleci.io/analyses/XZoMPq to pass StyleCI ?
