### ISSUE TITLE
Remove assetic from Symfony recipe?

### ISSUE THREAD

**Issue by garak** [deployphp/deployer#419]
Symfony recipe currently forces to use assetic. I think this a bit rude, since assetic is absolutely not mandatory for a Symfony project.
It would be nice to remove from main task, maybe adding a note in documentation suggesting to possibly enable 'deploy:assetic:dump' using `after` function.
A possible alternate solution is setting a boolean configuration variable, so you can disable/enable assetic in Symfony (this is how capifony does)

**Comment by elfet** [comment]
I think we need to investigate how to do it best.
ping @deployphp/maintainer

**Comment by elfet** [comment]
I think we need to investigate how to do it best.
ping @deployphp/maintainer

**Comment by ZeeCoder** [comment]
To be honest I build by assets by gulp on every deployment on the server-side, so I don't use assetic either.
The simplest solution could be to separate the assetic part into a separate recipe, but this would of course would be a BC break.

Another solution that's a non-breaking change could be achieved using global variables, so that if something like: "sf_skip_assetic" was set to true, then the task would do nothing.
It's not the nicest solution, since the task itself would still run, pretending to build assets, but in reality it would do nothing.

**Comment by elfet** [comment]
symfony.php has it’s own setting list. May be add it there?

**Comment by ZeeCoder** [comment]
Sure

**Comment by ihsanudin** [comment]
+1

**Comment by hason** [comment]
:+1:

**Comment by JHGitty** [comment]
Assetic has been removed from Symfony Standard Edition for Symfony >= 2.8 **as default**.
I think the recipe should only contain the basics of Symfony against the newest Symfony Standard Edition.

**Comment by dvzzz** [comment]
Symfony 2.8.0

```
  [RuntimeException]                                                  
                                                                      
    [Symfony\Component\Console\Exception\CommandNotFoundException]    
    There are no commands defined in the "assetic" namespace.         
    Did you mean this?                                                
        assets
```

**Comment by garak** [comment]
Maybe you closed it too fast? There is no mention about the new option added in #499 in docs.

**Comment by elfet** [comment]
Agree. Need to update docs.

**Comment by elfet** [comment]
Lets turn off assetic by default.
