### ISSUE TITLE
User uploads

### ISSUE THREAD

**Issue by jakenoble** [deployphp/deployer#426]
My user uploads reside in my web dir, is there a known way of handling this data during deployment so its not overwritten and lost on each deployment?

**Comment by oanhnn** [comment]
You can using `shared_dirs`:
```
set('shared_dirs', [
    'web/upload',
]);
```
http://deployer.org/docs/recipes

**Comment by jakenoble** [comment]
Ah right. Good to know I missed the line....

 > shared - contains shared/common files and directories between releases (logs, shared data, etc.).

Does that simply mean that those directories will be maintained and undisturbed during deployment?

**Comment by johnny-bit** [comment]
ummm... no.

That means that in directory `shared` there'll be created `web/upload` dir structure and upon deploment `web/upload` in uployed will be a symlink to `shared/web/upload'

If You're starting to use deployer instead of handling shared from get-go it would be wise to manually perform creation of `shared/web/upload` and placing files in it, because on first deploy actuall dir will get removed.

that basically means that files and directories are preserved, but outside of deployment moves, simply by symlinking to them.

**Comment by jakenoble** [comment]
OK thanks. That makes sense and further investigation shows this to be the case.

I can see how to do this migration now, copying files first to ensure they are not lost then the symlink will take care of future uploads as the symlink will be in place.
