### ISSUE TITLE
Is it possible to run a build task locally just once, and then deploy to many servers in the same deploy?

### ISSUE THREAD

**Issue by philbates35** [deployphp/deployer#549]
I have a multi-tenant application, each tenant has their own instance of the application.

Currently we do a separate deployment for each application, but this results in a separate `composer install`, `npm install` etc for every tenant, and as the number of tenants grows this is taking too long.

I would like Deployer to sit on a build server, and run `composer install`, `npm install`, `gulp` etc in the release directory locally. **This should only happen once on the build server.** Then when that is done, I want to upload the entire release directory (include Composer's `vendor` directory and all built assets`) from the build server to the release directory on each of the tenant application servers. This means the build process only happens once, and will drastically speed up deployment time.

I've looked at the `local` recipe provided by the `deployphp/recipes` package, but from what I can see, all `runLocally` tasks run once for every server, which I don't want - I want the build process to happen only once.

I've also seen that I can define a task to run locally only once using `task()->once()` - the problem with this is that because there is no environment available when I define a task as `once`, I get an error `Call to a member function parse() on a non-object in /home/www/deployer/vendor/deployer/deployer/src/functions.php on line 316` when I try and `runLocally()` in the task that should run only once.

Here's some psudo-code for what I'd like to be able to do, but as far as I can see isn't possible.

```
// This task should only be run once locally, regardless of how many servers there are
task('local:build', function() {
    runLocally('cd {{local_release_path}} && composer install --no-dev);
    runLocally('cd {{local_release_path}} && npm install --production);
    runLocally('cd {{local_release_path}} && gulp);
})->once();
```
Does this make sense? And if so, is there a way that I've missed to achieve what I want? Or is this currently not possible?

Great project btw :)

**Comment by irfan** [comment]
I think this is much better than what I thought.

I just sent a PR for cluster feature, which allows you to define multiple servers with in the same call, but the thing that you mention what it's should be.. Better run once in the build server which will guarantee that all the seevers are gonna use same code base..

I think instead of user defined function we can add a deployment option. Dunno atm, just thoughts..

**Comment by irfan** [comment]
I think this is much better than what I thought.

I just sent a PR for cluster feature, which allows you to define multiple servers with in the same call, but the thing that you mention what it's should be.. Better run once in the build server which will guarantee that all the seevers are gonna use same code base..

I think instead of user defined function we can add a deployment option. Dunno atm, just thoughts..

**Comment by philbates35** [comment]
Yeah I saw your cluster PR and initially thought that that would solve my problem, but unfortunately it doesn't for the following reasons:
- The `deploy_path` environment variable is still variable depending on the server, so I would still need a way to define all environment variables on a per-server basis - from what I can see, all servers in each cluster would have to have the same environment variables.
- Like I alluded to in my post, the local build tasks (`composer install` etc) should happen only once, and the resulting build application then copied (e.g. via `rsync`) to each server.

Being able to ensure that all servers are going to use the same code base (like you mentioned), and at the same time dramatically cut down on deployment time (only have to `composer install` once, not once per server), while having the flexibility to set environment variables per-server, would be perfect.

When you say deployment option, do you mean that I could run something like `php vendor/bin/dep deploy --build-local production` to tell certain build tasks to run locally and only once (regardless of how many servers there are). If the option isn't provided, then the build tasks would run once per server. Is that what you were suggesting?

**Comment by irfan** [comment]
I agreed a part of your thoughts..  deploy_path consistency helps a lot.

- It's always better to keep same deploy_path for all the servers in the same cluster, that will help you to figure out your way around when you will need to dig a node. I can't imagine that a cluster have 8-10 nodes and some have different deploy_path.
- You can use config server to make a change on all the nodes and the deploy_path would be a part of it.
- In a cloud structure, you can clone a node easly to have a new node in the same cluster.
-----
When it comes to the build process, I totally agree with you. Build process should be done once in local environment.
Example:
- run composer in local
- prepare configs in local
- create cache directories etc.. in local
- check permissions in local
- create archive in local
- ship to those nodes
- expand archive in the node
- make changes if you need
- link the new application

As far as I see to make this happen needs quite lots change in the Deployer. I couldn't see a way to implement this right away. **Any help to show the way of how to implement very appreciated**
-----
Instead of creating "runLocally" function, I was thinking "an option" way to define where a task is going to trigger like in the yaml file. These kind of functions would be trouble in future, its not easy to test, there is no way to make a private function etc..

I think we can refactor some part of the code to be able to implement new features in elegant way.

Again, just thoughts, don't have any good idea atm..

**Comment by philbates35** [comment]
Regarding a variable deploy path, in my specific case we have a single dedicated server that will serve up to about 50 instances of the application (`/var/www/client1/`, `/var/www/client2` etc.). So I would need to set up a different Deployer `server()` for each client, all of which souls be identical except for the `deploy_path`.

Yes, your example build process is exactly the sort of thing I'm looking for!

**Comment by clphillips** [comment]
Ideally you should be building your software using Jenkins, Bamboo, or some other build server. Get your archive built (composer, npm, gulp, etc.), then simply run deployer to push the archive to each of your instances.

That said, you could accomplish what you're looking for using two separate deployer configs. Have one handle the build on your local machine, and another handle your actual deployments. To automate it, you'd want a script to handle both tasks sequentially, but basically you'd do this:

Build locally
```sh
dep build -f localbuild.php
```
Deploy to all environments
```sh
dep deploy -f deploy.php
```

**Comment by philbates35** [comment]
With the Jenkins option: Do you mean Jenkins and Deployer would be in the same server, and Jenkins as it's last build step would talk to Deployer, which would look in the Jenkins build directory and just copy (rsync etc) the archive to the servers?

With the two deploy files option - I guess the `buildLocally.php` file wouldn't have any servers defined to ensure that the tasks are executed only once. If that's the case - what would my tasks look like in the `buildLocally` file? Any chance you can give a quick psudo code example?

**Comment by clphillips** [comment]
> Do you mean Jenkins and Deployer would be in the same server, and Jenkins as it's last build step would talk to Deployer, which would look in the Jenkins build directory and just copy (rsync etc) the archive to the servers?

Yes, precisely. I'd recommend using the deployer PHAR for this purpose. If you're using ANT, your target might look like:

```xml
    <target name="deploy" description="Deploy using Deployer">
        <exec executable="dep">
            <arg value="deploy" />
            <arg value="-f deploy.php" />
        </exec>
    </target>
```

If you choose to use deployer to build your project as well (which I don't recommend because Jenkins does this so much easier), your *localbuild.php* might look something like:

```php
<?php
require 'recipe/common.php';

localServer('local')
    ->env('deploy_path', './build/dist')
    ->stage('local');

task('composer', function () {
    run('composer install --prefer-dist --no-interaction');
});

task('npm', function () {
    run('npm install');
});

task('gulp', function () {
    run('gulp');
});

task('archive', function () {
   // do whatever you need to do archive files
});

task('build', [
    'composer',
    'npm',
    'gulp',
    'archive'
]);
```
