### ISSUE TITLE
Task common - deploy lock - where is documentation on it? 

### ISSUE THREAD

**Issue by tebaly** [deployphp/deployer#933]
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 4.0.2
| Local Machine OS  | N/A
| Remote Machine OS | N/A

Hello. 

Task common - deploy:lock - where is documentation on it? 

https://github.com/deployphp/deployer/blob/v4.0.2/recipe/deploy/lock.php

Please add at least a couple of words in each task. For example

```
/* (c) Anton Medvedev <anton@medv.io>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 * 
 * This task for ....
 */
```

Please.

**Comment by elfet** [comment]
Will add docs on site and in code too.

**Comment by pluseg** [comment]
@tebally What kind of branching do you use? Common branches or bookmarks?

**Comment by pluseg** [comment]
@elfet Please approve that this is for preventing concurrent deployment processes of same project and server? If this is correct, I will add it into https://github.com/deployphp/deployer/blob/v4.0.2/recipe/deploy/lock.php annotation. I guess that there is no need to describe it in docs because of it's internal thing. What do you think?

**Comment by elfet** [comment]
> Please approve that this is for preventing concurrent deployment processes of same project and server?
Yes. Docs now is here: https://deployer.org/docs/flow

**Comment by pluseg** [comment]
@elfet nice! Then let's close this ticket.
